name: 🚀 SSH Deploy Only

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🚀 Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          echo "🔄 Starting deployment..."

          # Navigate to project directory
          cd ${{ secrets.PROJECT_PATH || '/var/www/html' }}

          # Pull latest changes
          git pull origin main || git pull origin master

          # Install/update dependencies
          composer install --no-dev --optimize-autoloader

          # Clear and cache config
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Run migrations
          php artisan migrate --force

          # Set permissions
          chmod -R 755 storage bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache

          echo "✅ Deployment completed successfully!"
